---
- name: Template
  hosts: all
  remote_user: root

  tasks:
  - debug:
      msg: System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }} has gateway {{ ansible_default_ipv4.gateway }}
