---
- name: Template
  hosts: all
  remote_user: root

  tasks:
  - name: Include a play after another play
    include: ping_include.yml
  - name: Changement permissions et owner
    file:
      path: /root/test.sh
      owner: user
      group: user
      mode: '0644'
